### ISSUE TITLE
Mining drill modes not switchable? [Unconfirmed]

### ISSUE THREAD

**Issue by Ekdohibs** [minetest-technic/technic#332] opened 2017-03-27 14:51 UTC
See http://irc.minetest.ru/minetest-project/2017-03-27#i_4840726

**Comment by kaeza** [comment] 2017-03-27 20:12
Cannot reproduce myself. All drills work as (what I suppose) is expected.

* Mk1 drill can't switch mode.
* Mk2 drill goes 1-4.
* Mk3 drill goes 1-5.

Am I missing something?

**Comment by thatgraemeguy** [comment] 2017-03-28 07:31
This was fixed in #314.

**Comment by kaeza** [comment] 2017-03-29 05:57
I guess this can be closed then. @Ekdohibs ?

**Closed** 2017-03-29 05:58 UTC
