### ISSUE TITLE
Constructor-machine crash the server

### ISSUE THREAD

**Issue by EuPhobos** [minetest-technic/technic#261] opened 2016-02-28 14:54 UTC
I tested with technic:constructor_mk3, if place some node in front of constructor - it dig it up, it's ok.
But if it node have "drop" parameter and extends drop with rarety which returns another object, then constructor crash the server, i tested it with carrots from farming_plus mod, and it always crash server.
Then i fast-created the simple mod and one node, with extend drop parameter and one rarety, constructor will dig normally until the trigger "rarety".
`2016-02-28 16:34:32: ERROR[main]: stack traceback:
2016-02-28 16:34:32: ERROR[main]:       [C]: in function 'remove_item'
2016-02-28 16:34:32: ERROR[main]:       ...game/mods/technic/technic/machines/other/constructor.lua:24: in function 'deploy_node'
2016-02-28 16:34:32: ERROR[main]:       ...game/mods/technic/technic/machines/other/constructor.lua:105: in function 'action_on'`

**Comment by VanessaE** [comment] 2017-03-06 19:40
Is this still a problem?

**Comment by kaeza** [comment] 2017-03-07 01:42
This seems to be still valid.

Steps I used to reproduce:

* Install `technic`, `mesecons`, and `farming_plus` (I assume you mean [PilzAdam/farming_plus](https://github.com/PilzAdam/farming_plus)).
* Place Constructor Mk3 and some activator.
* Execute `/giveme farming_plus:carrot` and place the resulting item in front of the constructor.
* Activate the constructor and watch it crash.

Full traceback:

```
2017-03-06 22:36:23: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'mesecons' in callback environment_Step(): Expecting itemstack, itemstring, table or nil
2017-03-06 22:36:23: ERROR[Main]: stack traceback:
2017-03-06 22:36:23: ERROR[Main]: 	[C]: in function 'remove_item'
2017-03-06 22:36:23: ERROR[Main]: 	.../mods/technic.mpk/technic/machines/other/constructor.lua:24: in function 'deploy_node'
2017-03-06 22:36:23: ERROR[Main]: 	.../mods/technic.mpk/technic/machines/other/constructor.lua:105: in function 'action_on'
2017-03-06 22:36:23: ERROR[Main]: 	.../minetest/bin/../mods/mesecons.mpk/mesecons/internal.lua:190: in function <.../minetest/bin/../mods/mesecons.mpk/mesecons/internal.lua:183>
2017-03-06 22:36:23: ERROR[Main]: 	...netest/bin/../mods/mesecons.mpk/mesecons/actionqueue.lua:93: in function 'execute'
2017-03-06 22:36:23: ERROR[Main]: 	...netest/bin/../mods/mesecons.mpk/mesecons/actionqueue.lua:84: in function <...netest/bin/../mods/mesecons.mpk/mesecons/actionqueue.lua:61>
2017-03-06 22:36:23: ERROR[Main]: 	.../minetest/bin/../builtin/game/register.lua:412: in function <.../minetest/bin/../builtin/game/register.lua:392>
```

**Comment by kaeza** [comment] 2017-03-07 02:06
Submitted a temporary patch that fixes the crash (https://github.com/minetest-technic/technic/commit/186f9b70ac9efef4a1672f6822e6c22d31928dc4), but now it does not want to dig the carrots.

Seems to work fine with e.g. leaves. I will investigate further and see what can be done.

Closing this for now. Thank you for reporting!

**Closed by kaeza** 2017-03-07 02:06 UTC
Labels: Bug

**Comment by HybridDog** [comment] 2017-03-07 08:52
> but now it does not want to dig the carrots.

The code lacks comments. If l understand it correctly, it adds the drops of the node to the inventory until it notices that the inventory isn't big enough. Then it removes the items it added hitherto from the inventory (and does not remove the node).
So the carrots drop too much (> 4 items which can't be stacked):
https://github.com/PilzAdam/farming_plus/blob/master/carrots.lua#L66

**Comment by Minetest-One** [comment] 2019-03-12 21:18
sorry, posted issues again, solution seams to be

replace nodeupdate with minetest.check_for_falling
(not tested yet)

**Comment by Festus1965** [comment] 2022-04-04 09:29
just a gamer from india "able29"
asked me to test if that issue is still there ... 
he claim a crash possible with constructor (1,2, or 3) dig a bucket of water (maybe dropped)

and then I see that this issue is 3 years open, no one tested ?
